// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ppm360.Data;

#nullable disable

namespace ppm360.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230604113616_PPM360Migration")]
    partial class PPM360Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ppm360.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Budget")
                        .HasColumnType("double precision");

                    b.Property<int>("BufferDays")
                        .HasColumnType("integer");

                    b.Property<double>("CapitalValue")
                        .HasColumnType("double precision");

                    b.Property<Dictionary<string, string>>("Comments")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<double>("CostReduction")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavings1")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavings2")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavings3")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavings4")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavings5")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("CustomerSatisfaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Digitalisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EverydayBenefit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutiveUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ExternalCost")
                        .HasColumnType("double precision");

                    b.Property<int>("ExternalStakeholders")
                        .HasColumnType("integer");

                    b.Property<double>("InternalCost")
                        .HasColumnType("double precision");

                    b.Property<double>("Investments")
                        .HasColumnType("double precision");

                    b.Property<string>("InvolvedBusinessUnits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PmWorkload")
                        .HasColumnType("integer");

                    b.Property<double>("ProjectCost")
                        .HasColumnType("double precision");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectManager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectRisk")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolutionScopeExtend")
                        .HasColumnType("integer");

                    b.Property<int>("SolutionScopeProcess")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("SupportExpense")
                        .HasColumnType("integer");

                    b.Property<string>("TeamSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TurnoverIncrease1")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverIncrease2")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverIncrease3")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverIncrease4")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverIncrease5")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ppm360.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
