// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ppm360.Data;

#nullable disable

namespace ppm360.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ppm360.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Budget")
                        .HasColumnType("double precision");

                    b.Property<int>("BufferDays")
                        .HasColumnType("integer");

                    b.Property<double>("CapitalValue")
                        .HasColumnType("double precision");

                    b.Property<List<Dictionary<string, string>>>("Comments")
                        .IsRequired()
                        .HasColumnType("hstore[]");

                    b.Property<double>("CostReduction")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavingsY1")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavingsY2")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavingsY3")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavingsY4")
                        .HasColumnType("double precision");

                    b.Property<double>("CostSavingsY5")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("CustomerSatisfaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Digitalisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EverydayBenefit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutiveUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ExternalCost")
                        .HasColumnType("double precision");

                    b.Property<int>("ExternalStakeholders")
                        .HasColumnType("integer");

                    b.Property<double>("InternalCost")
                        .HasColumnType("double precision");

                    b.Property<double>("Investments")
                        .HasColumnType("double precision");

                    b.Property<string>("InvolvedBusinessUnits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductManagerWorkload")
                        .HasColumnType("integer");

                    b.Property<double>("ProjectCost")
                        .HasColumnType("double precision");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectManager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectRisk")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SolutionScopeFunctional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SolutionScopeProcess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("SupportEffort")
                        .HasColumnType("integer");

                    b.Property<string>("TeamSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TurnoverIncreaseY1")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverIncreaseY2")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverIncreaseY3")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverIncreaseY4")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverIncreaseY5")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ppm360.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
